service: scene-finder-function

provider:
  name: aws
  runtime: nodejs8.10
  profile: scene-finder-function  # Default: default
  region: ${opt:region, 'ap-northeast-1'}  # Default: us-east-1
  stage: ${opt:region, 'beta'}  # Default: dev

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  domains:
    prod: sf-func.api.yokrh.com
    beta: sf-func-beta.api.yokrh.com
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    certificateName: '*.api.yokrh.com'
    stage: ${self:provider.stage}
    basePath: ''
    createRoute53Record: false  # Default: true.
    #Creating a new Route53 record in other account is not supported.
    #Should add A record with alias manually from https://console.aws.amazon.com/route53/home#hosted-zones:
    #Issue: https://github.com/amplify-education/serverless-domain-manager/issues/233

package:
  exclude:
    - ./**/.DS_Store
    - package.json
    - package-lock.json
    - static/bin/opencv/cv2/data/
    - static/bin/**/__pycache__/
    - static/bin/opencv/numpy/**/tests/
  include:
    # - node_modules/**
    - static/**
    - model/**
    - index.js
    - app.js

functions:
  fc-index:
    handler: index.handler
    events:
      - http:
          method: options
          path: /{proxy+}  # catch-all path
      - http:
          method: get
          path: /{proxy+}  # catch-all path
